export default {
    "index": "Home",
    "getting_started": "Getting Started",
    "day1": "Day 1 - Introduction to DSA",
    "day2": "Day 2 - Arrays and Strings",
    "day3": "Day 3 - Linked Lists",
    "day4": "Day 4 - Stacks and Queues",
    "day5": "Day 5 - Recursion",
    "day6": "Day 6 - Binary Trees and BST",
    "day7": "Day 7 - Heaps and Priority Queues",
    "day8": "Day 8 - Hash Tables and Hash Functions",
    "day9": "Day 9 - Graphs (Basics)",
    "day10": "Day 10 - Graph Traversal (DFS and BFS)",
    "day11": "Day 11 - Sorting Algorithms - I",
    "day12": "Day 12 - Sorting Algorithms - II",
    "day13": "Day 13 - Searching Algorithms",
    "day14": "Day 14 - Dynamic Programming",
    "day15": "Day 15 - Greedy Algorithms",
    "day16": "Day 16 - Backtracking",
    "day17": "Day 17 - Bit Manipulation",
    "day18": "Day 18 - Tries",
    "day19": "Day 19 - Segment Trees",
    "day20": "Day 20 - Union Find",
    "day21": "Day 21 - Shortest Paths",
    "day22": "Day 22 - Minimum Spanning Trees",
    "day23": "Day 23 - Topological Sort",
    "day24": "Day 24 - Sliding Window",
    "day25": "Day 25 - Two Pointers",
    "day26": "Day 26 - Divide & Conquer",
    "day27": "Day 27 - Advanced Strings",
    "day28": "Day 28 - System Design 101",
    "day29": "Day 29 - Mock Interview",
    "day30": "Day 30 - Victory Lap",
    "github_link": {
        "title": "DSA-30",
        "href": "https://github.com/Archit1706/DSA-30",
        "newWindow": true
    }
}
